# PR Pipeline — Customer Registry
# Runs on every pull request targeting main.
# Gates: build, test, architecture verification, security scanning.

trigger: none

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - '*.md'
      - 'docs/**'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: NPM_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.npm

stages:
  # ══════════════════════════════════════════════════════════════
  # Stage 1: Build and Test (Java + Angular in parallel)
  # ══════════════════════════════════════════════════════════════
  - stage: BuildAndTest
    displayName: 'Build & Test'
    jobs:
      - job: JavaBuild
        displayName: 'Java Build & Test'
        steps:
          - task: Cache@2
            displayName: 'Cache Maven repository'
            inputs:
              key: 'maven | "$(Agent.OS)" | pom.xml | customer-registry-starter/pom.xml'
              path: $(MAVEN_CACHE_FOLDER)

          - template: templates/java-build.yml
            parameters:
              mavenGoals: 'clean verify -Dtest=!*IntegrationTest -Dsurefire.failIfNoSpecifiedTests=false'
              publishTestResults: true

      - job: AngularBuild
        displayName: 'Angular Build & Test'
        steps:
          - task: Cache@2
            displayName: 'Cache npm'
            inputs:
              key: 'npm | "$(Agent.OS)" | frontend/package-lock.json'
              path: $(NPM_CACHE_FOLDER)

          - template: templates/angular-build.yml
            parameters:
              runTests: true
              buildLibrary: true

  # ══════════════════════════════════════════════════════════════
  # Stage 2: Architecture Verification
  # ══════════════════════════════════════════════════════════════
  - stage: ArchitectureVerification
    displayName: 'Architecture Verification'
    dependsOn: BuildAndTest
    jobs:
      - job: ArchUnit
        displayName: 'ArchUnit & Spring Modulith Verify'
        steps:
          - task: Cache@2
            displayName: 'Cache Maven repository'
            inputs:
              key: 'maven | "$(Agent.OS)" | pom.xml | customer-registry-starter/pom.xml'
              path: $(MAVEN_CACHE_FOLDER)

          - task: MavenAuthenticate@0
            displayName: 'Authenticate Maven feed'
            inputs:
              artifactsFeeds: 'customer-registry-feed'

          - task: Maven@4
            displayName: 'Run ArchUnit + Modulith tests'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'
              options: '-pl customer-registry-starter -Dtest=*StructureTest,*ArchitectureTest -Dsurefire.failIfNoSpecifiedTests=false'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.21'

  # ══════════════════════════════════════════════════════════════
  # Stage 3: Security Scanning (SAST + SCA + SBOM)
  # ══════════════════════════════════════════════════════════════
  - stage: SecurityScanning
    displayName: 'Security Scanning'
    dependsOn: BuildAndTest
    jobs:
      - job: SecurityScan
        displayName: 'SAST + SCA + SBOM'
        steps:
          - task: Cache@2
            displayName: 'Cache Maven repository'
            inputs:
              key: 'maven | "$(Agent.OS)" | pom.xml | customer-registry-starter/pom.xml'
              path: $(MAVEN_CACHE_FOLDER)

          - task: MavenAuthenticate@0
            displayName: 'Authenticate Maven feed'
            inputs:
              artifactsFeeds: 'customer-registry-feed'

          - task: Npm@1
            displayName: 'npm ci (for audit)'
            inputs:
              command: 'ci'
              workingDir: 'frontend'

          - template: templates/security-scan.yml
            parameters:
              failOnHighCvss: 7

  # ══════════════════════════════════════════════════════════════
  # Stage 4: Quality Gate
  # ══════════════════════════════════════════════════════════════
  - stage: QualityGate
    displayName: 'Quality Gate'
    dependsOn:
      - BuildAndTest
      - ArchitectureVerification
      - SecurityScanning
    condition: succeeded()
    jobs:
      - job: Gate
        displayName: 'All checks passed'
        steps:
          - script: echo "All quality gates passed. PR is ready for review."
            displayName: 'Quality Gate OK'
