# Release Pipeline — Customer Registry
# Triggers on tags matching v* (e.g., v1.0.0, v1.2.3).
# Publishes Maven + npm artifacts to Azure Artifacts feeds.

trigger:
  tags:
    include:
      - 'v*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: NPM_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.npm
  - name: IS_TAG
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/v')]

stages:
  # ══════════════════════════════════════════════════════════════
  # Stage 1: Extract Version from Git Tag
  # ══════════════════════════════════════════════════════════════
  - stage: Version
    displayName: 'Extract Version'
    jobs:
      - job: ExtractVersion
        displayName: 'Parse version from git tag'
        steps:
          - script: |
              TAG_NAME=$(echo "$(Build.SourceBranch)" | sed 's|refs/tags/v||')
              echo "##vso[task.setvariable variable=RELEASE_VERSION;isOutput=true]${TAG_NAME}"
              echo "Release version: ${TAG_NAME}"
            name: version
            displayName: 'Extract version from tag'

  # ══════════════════════════════════════════════════════════════
  # Stage 2: Build and Verify (same as PR pipeline)
  # ══════════════════════════════════════════════════════════════
  - stage: BuildVerify
    displayName: 'Build & Verify'
    dependsOn: Version
    variables:
      RELEASE_VERSION: $[stageDependencies.Version.ExtractVersion.outputs['version.RELEASE_VERSION']]
    jobs:
      - job: JavaBuild
        displayName: 'Java Build & Test'
        steps:
          - task: Cache@2
            displayName: 'Cache Maven repository'
            inputs:
              key: 'maven | "$(Agent.OS)" | pom.xml | customer-registry-starter/pom.xml'
              path: $(MAVEN_CACHE_FOLDER)

          - task: MavenAuthenticate@0
            displayName: 'Authenticate Maven feed'
            inputs:
              artifactsFeeds: 'customer-registry-feed'

          - task: Maven@4
            displayName: 'Maven clean verify'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean verify'
              options: '-Drevision=$(RELEASE_VERSION) -Dtest=!*IntegrationTest -Dsurefire.failIfNoSpecifiedTests=false'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.21'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'

      - job: AngularBuild
        displayName: 'Angular Build & Test'
        steps:
          - task: Cache@2
            displayName: 'Cache npm'
            inputs:
              key: 'npm | "$(Agent.OS)" | frontend/package-lock.json'
              path: $(NPM_CACHE_FOLDER)

          - template: templates/angular-build.yml
            parameters:
              runTests: true
              buildLibrary: true

      - job: SecurityScan
        displayName: 'Security Scan'
        steps:
          - task: Cache@2
            displayName: 'Cache Maven repository'
            inputs:
              key: 'maven | "$(Agent.OS)" | pom.xml | customer-registry-starter/pom.xml'
              path: $(MAVEN_CACHE_FOLDER)

          - task: MavenAuthenticate@0
            displayName: 'Authenticate Maven feed'
            inputs:
              artifactsFeeds: 'customer-registry-feed'

          - task: Npm@1
            displayName: 'npm ci'
            inputs:
              command: 'ci'
              workingDir: 'frontend'

          - template: templates/security-scan.yml
            parameters:
              failOnHighCvss: 7

  # ══════════════════════════════════════════════════════════════
  # Stage 3: Publish Artifacts
  # ══════════════════════════════════════════════════════════════
  - stage: Publish
    displayName: 'Publish Artifacts'
    dependsOn: BuildVerify
    condition: and(succeeded(), eq(variables.IS_TAG, 'true'))
    variables:
      RELEASE_VERSION: $[stageDependencies.Version.ExtractVersion.outputs['version.RELEASE_VERSION']]
    jobs:
      - job: PublishMaven
        displayName: 'Publish Maven Artifacts'
        steps:
          - task: Cache@2
            displayName: 'Cache Maven repository'
            inputs:
              key: 'maven | "$(Agent.OS)" | pom.xml | customer-registry-starter/pom.xml'
              path: $(MAVEN_CACHE_FOLDER)

          - task: MavenAuthenticate@0
            displayName: 'Authenticate Maven feed'
            inputs:
              artifactsFeeds: 'customer-registry-feed'

          - task: Maven@4
            displayName: 'Maven deploy'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'deploy'
              options: '-Drevision=$(RELEASE_VERSION) -DskipTests -DaltDeploymentRepository=customer-registry-feed::default::$(MAVEN_FEED_URL)'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.21'

      - job: PublishNpm
        displayName: 'Publish npm Package'
        steps:
          - task: Cache@2
            displayName: 'Cache npm'
            inputs:
              key: 'npm | "$(Agent.OS)" | frontend/package-lock.json'
              path: $(NPM_CACHE_FOLDER)

          - task: npmAuthenticate@0
            displayName: 'Authenticate npm feed'
            inputs:
              workingFile: 'frontend/.npmrc'

          - task: Npm@1
            displayName: 'npm ci'
            inputs:
              command: 'ci'
              workingDir: 'frontend'

          - script: |
              cd frontend
              npx ng build customer-registry-ui --configuration production
              cd dist/customer-registry-ui
              npm version $(RELEASE_VERSION) --no-git-tag-version
              npm publish
            displayName: 'Build and publish npm package'

      - job: PublishSBOM
        displayName: 'Publish SBOM'
        steps:
          - task: Cache@2
            displayName: 'Cache Maven repository'
            inputs:
              key: 'maven | "$(Agent.OS)" | pom.xml | customer-registry-starter/pom.xml'
              path: $(MAVEN_CACHE_FOLDER)

          - task: MavenAuthenticate@0
            displayName: 'Authenticate Maven feed'
            inputs:
              artifactsFeeds: 'customer-registry-feed'

          - task: Maven@4
            displayName: 'Generate Java SBOM'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'org.cyclonedx:cyclonedx-maven-plugin:makeBom'
              options: '-Drevision=$(RELEASE_VERSION)'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.21'

          - script: |
              cd frontend
              npm ci
              npx @cyclonedx/cdxgen -o ../sbom-frontend.json
            displayName: 'Generate Angular SBOM'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish backend SBOM'
            inputs:
              PathtoPublish: 'target/bom.json'
              ArtifactName: 'sbom-backend-$(RELEASE_VERSION)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish frontend SBOM'
            inputs:
              PathtoPublish: 'sbom-frontend.json'
              ArtifactName: 'sbom-frontend-$(RELEASE_VERSION)'
